### ISSUE TITLE
Start syncthing on boot?

### ISSUE THREAD

**Issue by ndguardian** [veckia9x/Trimui-X#1]
Howdy!

First off, great work so far on getting syncthing working on the TrimUI Smart Pro. I'm a fan! That said, would you happen to know a way to get it set up to start on boot? That would be a nice QoL improvement.

**Comment by veckia9x** [comment]
Thanks, I appreciate the compliment!
Yes, theres away to start it at boot, you just need to put a start script in the `System/starts` but it cannot be the same script in Apps because the way it works, it sometimes will think the syncthing is already started and do nothing.

I'll add an option to this in the next update, in a few days hopefully.

**Comment by ndguardian** [comment]
Okay, cool! I might try that out tomorrow since it's late here, but I'll be interested to see if you get something whipped up.

**Comment by veckia9x** [comment]
Feature added, read the readme for instructions, new release available. :)

**Comment by ndguardian** [comment]
Got the new release installed. Seems like something might be up with the actual copy command since even though I set the option to "yes", it didn't start on boot. When I followed what the script was doing though and I manually copied the sync_boot script over to System/starts, all worked as expected. That's a huge relief since I use that to sync up my saves between devices.

**Comment by veckia9x** [comment]
Ok, ill take a look at it.
When i tested everything was working, and i tested a few times (had a bug that the sync_boot.sh wasnt being copied on my end too, same issue reaslly, but i fixed)

Can you give me more details on your system, wich os/cfw you're using, did you tried tomatoOS or another before and did you reflash your firmware after it and before your current OS/cfw?

**Comment by ndguardian** [comment]
Hey, so I'm happy to share any details you need. Basically I got it like a month ago and went straight to the latest version of tomato available at that time, and I've stuck with it since.

**Comment by veckia9x** [comment]
Tested just now and I cant seen to find any errors with it... =/

Did you had a clean install of the syncthing ?
(deleted the folder `syncthing` inside `System/` folder on root of sd card? Witha  bkp of the said folder/files)

Because the boot option is only taken in consideration when installing the syncthing. otherwise ignored.

Let me know! Thanks!

**Comment by ndguardian** [comment]
Ah, I was wondering if that might be the case. Nah I didn't do a clean install, rather I just basically copied over the new app version. So yeah, that's very much likely a me problem rather than the app. New users of the app likely won't have that issue.

Appreciate the help on this, and you're awesome!

**Comment by ndguardian** [comment]
Hope you don't mind, but I'm going to set up a copy of this repo. I managed to get Syncthing running on the OG TrimUI Smart with a couple minor modifications to your script and I want to share that out. The pretty GUI elements and auto-start don't seem to work, but hey I'll call it a win!

I'll make sure to credit you and the folks you credited in your readme so people can be aware of your awesome work.

**Comment by veckia9x** [comment]
Yeah, I dont mind at all, =), I was going to do that myself since Im working on a stock mod os myself. (only a few ppl know this)
As for the other stuff not working on stock, I'll add the compatibility for it on the next update, I just need time to finish my scraper for the tsp.

edit: you could also send a pull request if you like. =)

**Comment by ndguardian** [comment]
Yeah, I could probably do that. Tell you what, I'll update the script to be unified, and then the user can just set which device they're running. Sound good? It's pretty similar overall so it shouldn't be hard.

**Comment by veckia9x** [comment]
oooohhh, you mean the first trimui! i get it now, feel free to do whatever you want man! since I dont have one i would be bad for me since I wouldnt be able to maintain it.

**Comment by ndguardian** [comment]
Ha and of course I just now see this after pushing it up. :D Well I can still keep it separate if you want, but I might do the unified thing just for my own sake.

**Comment by veckia9x** [comment]
ok, lol, let me take a look into it, there might be a way to identify each device.

**Comment by ndguardian** [comment]
I leave that up to the user for now in the options file. Here's what I've got so far, but I need to test and make sure all works as expected on both devices. https://github.com/ndguardian/Trimui-X/tree/syncthing-unified/Apps/Syncthing

**Comment by veckia9x** [comment]
do you have a discord or something? I'm interested, like og trimui uses the same folder structure? does it use the tina linux too? besides from it having a small screen and no analog joysticks i know nothing about it.

**Comment by ndguardian** [comment]
Yep, I do have discord and just sent over a friend invite. 

At first glance, it does seem like it's pretty much the same OS and folder structure under the hood. It seems to be missing that sdl2imgshow binary (I think) that you use in the syncthing script, so there are likely some differences. And the fact that the processors are a slightly different architecture. The pro uses aarch64 and the og uses armv7.
